window.OT_DOCUMENTS = [
  {
    "id": 1,
    "category": "Ordenamiento Territorial",
    "section": "Marco Normativo",
    "group": "Normativa",
    "name": "ORDENANZA O0015-2017 APROBACION DE LA ZEE",
    "type": "Documento",
    "format": "PDF",
    "study": "Normativa",
    "driveId": "1CXczQSJq7W2S2RYXo79K3pT3ry4zWA9v",
    "viewUrl": "https://drive.google.com/file/d/1CXczQSJq7W2S2RYXo79K3pT3ry4zWA9v/view",
    "previewUrl": "https://drive.google.com/file/d/1CXczQSJq7W2S2RYXo79K3pT3ry4zWA9v/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1CXczQSJq7W2S2RYXo79K3pT3ry4zWA9v"
  },
  {
    "id": 2,
    "category": "Ordenamiento Territorial",
    "section": "Marco Normativo",
    "group": "Normativa",
    "name": "ORDENANZA O0009-2020 REGLAMENTO COMISION TECNICA REGIONAL",
    "type": "Documento",
    "format": "PDF",
    "study": "Normativa",
    "driveId": "1VvIuKzc04clumqJ74OPCxkuV_n5kN7jl",
    "viewUrl": "https://drive.google.com/file/d/1VvIuKzc04clumqJ74OPCxkuV_n5kN7jl/view",
    "previewUrl": "https://drive.google.com/file/d/1VvIuKzc04clumqJ74OPCxkuV_n5kN7jl/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1VvIuKzc04clumqJ74OPCxkuV_n5kN7jl"
  },
  {
    "id": 3,
    "category": "Ordenamiento Territorial",
    "section": "Marco Normativo",
    "group": "Normativa",
    "name": "ORDENANZA 0006-2020 ZEE NUEVA APLICACION",
    "type": "Documento",
    "format": "PDF",
    "study": "Normativa",
    "driveId": "1L196sDCyFCp64yUSD7Kv237TWbXrNFvV",
    "viewUrl": "https://drive.google.com/file/d/1L196sDCyFCp64yUSD7Kv237TWbXrNFvV/view",
    "previewUrl": "https://drive.google.com/file/d/1L196sDCyFCp64yUSD7Kv237TWbXrNFvV/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1L196sDCyFCp64yUSD7Kv237TWbXrNFvV"
  },
  {
    "id": 4,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "ZEE",
    "name": "Memoria ZEE Ucayali",
    "type": "Documento",
    "format": "PDF",
    "study": "ZEE",
    "driveId": "1g8xLNwyS7I9XMK07R5Vthc44us5f2vTL",
    "viewUrl": "https://drive.google.com/file/d/1g8xLNwyS7I9XMK07R5Vthc44us5f2vTL/view",
    "previewUrl": "https://drive.google.com/file/d/1g8xLNwyS7I9XMK07R5Vthc44us5f2vTL/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1g8xLNwyS7I9XMK07R5Vthc44us5f2vTL"
  },
  {
    "id": 5,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Submodelos",
    "name": "1 SM VPRN Renovables",
    "type": "Documento",
    "format": "PDF",
    "study": "VPRN Renovables",
    "driveId": "13NpRUfldU5dktnR_dHoinvUvRrZIjxhr",
    "viewUrl": "https://drive.google.com/file/d/13NpRUfldU5dktnR_dHoinvUvRrZIjxhr/view",
    "previewUrl": "https://drive.google.com/file/d/13NpRUfldU5dktnR_dHoinvUvRrZIjxhr/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=13NpRUfldU5dktnR_dHoinvUvRrZIjxhr"
  },
  {
    "id": 6,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Submodelos",
    "name": "2 SM VPRN no Renovables",
    "type": "Documento",
    "format": "PDF",
    "study": "VPRN no Renovables",
    "driveId": "1zMTOdqP1jg-Rp0CK9cXznpVfFCDiLFXL",
    "viewUrl": "https://drive.google.com/file/d/1zMTOdqP1jg-Rp0CK9cXznpVfFCDiLFXL/view",
    "previewUrl": "https://drive.google.com/file/d/1zMTOdqP1jg-Rp0CK9cXznpVfFCDiLFXL/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1zMTOdqP1jg-Rp0CK9cXznpVfFCDiLFXL"
  },
  {
    "id": 7,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Submodelos",
    "name": "3 SM V Bioecológico",
    "type": "Documento",
    "format": "PDF",
    "study": "Valor Bioecológico",
    "driveId": "1P6BoctKKYb-n1R_SnZMfS-knXbYghf65",
    "viewUrl": "https://drive.google.com/file/d/1P6BoctKKYb-n1R_SnZMfS-knXbYghf65/view",
    "previewUrl": "https://drive.google.com/file/d/1P6BoctKKYb-n1R_SnZMfS-knXbYghf65/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1P6BoctKKYb-n1R_SnZMfS-knXbYghf65"
  },
  {
    "id": 8,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Submodelos",
    "name": "4 SM CU Tierra",
    "type": "Documento",
    "format": "PDF",
    "study": "Conflicto de Uso de la Tierra",
    "driveId": "12k_A8DG6YP9uMUBN8sLAnKfumVz2aCsx",
    "viewUrl": "https://drive.google.com/file/d/12k_A8DG6YP9uMUBN8sLAnKfumVz2aCsx/view",
    "previewUrl": "https://drive.google.com/file/d/12k_A8DG6YP9uMUBN8sLAnKfumVz2aCsx/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=12k_A8DG6YP9uMUBN8sLAnKfumVz2aCsx"
  },
  {
    "id": 9,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Submodelos",
    "name": "5 SM AU Industrial",
    "type": "Documento",
    "format": "PDF",
    "study": "Aptitud Urbano Industrial",
    "driveId": "1akSoANBvxjgOAHmG4fGIsWuVectib6Ni",
    "viewUrl": "https://drive.google.com/file/d/1akSoANBvxjgOAHmG4fGIsWuVectib6Ni/view",
    "previewUrl": "https://drive.google.com/file/d/1akSoANBvxjgOAHmG4fGIsWuVectib6Ni/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1akSoANBvxjgOAHmG4fGIsWuVectib6Ni"
  },
  {
    "id": 10,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Submodelos",
    "name": "6 SM Peligros múltiples",
    "type": "Documento",
    "format": "PDF",
    "study": "Peligros Múltiples",
    "driveId": "1oeKnG2SIQqCq0D-bMrBizwPakeKzc_Hj",
    "viewUrl": "https://drive.google.com/file/d/1oeKnG2SIQqCq0D-bMrBizwPakeKzc_Hj/view",
    "previewUrl": "https://drive.google.com/file/d/1oeKnG2SIQqCq0D-bMrBizwPakeKzc_Hj/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1oeKnG2SIQqCq0D-bMrBizwPakeKzc_Hj"
  },
  {
    "id": 11,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Submodelos",
    "name": "7 SM Vulnerabilidad",
    "type": "Documento",
    "format": "PDF",
    "study": "Vulnerabilidad",
    "driveId": "115BIx_7Q3F0xfs108-cI8H_Zx0Gy2zHA",
    "viewUrl": "https://drive.google.com/file/d/115BIx_7Q3F0xfs108-cI8H_Zx0Gy2zHA/view",
    "previewUrl": "https://drive.google.com/file/d/115BIx_7Q3F0xfs108-cI8H_Zx0Gy2zHA/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=115BIx_7Q3F0xfs108-cI8H_Zx0Gy2zHA"
  },
  {
    "id": 12,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Submodelos",
    "name": "8 SM VH Cultural",
    "type": "Documento",
    "format": "PDF",
    "study": "Valor Histórico Cultural",
    "driveId": "1EAncRPj57NyealstMZf2Q1SUaPeuEf8O",
    "viewUrl": "https://drive.google.com/file/d/1EAncRPj57NyealstMZf2Q1SUaPeuEf8O/view",
    "previewUrl": "https://drive.google.com/file/d/1EAncRPj57NyealstMZf2Q1SUaPeuEf8O/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1EAncRPj57NyealstMZf2Q1SUaPeuEf8O"
  },
  {
    "id": 13,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Submodelos",
    "name": "9 SM P SEconómicas",
    "type": "Documento",
    "format": "PDF",
    "study": "Potencialidades Socioeconómicas",
    "driveId": "1WXjAKEJ2bZ4fRZsRQrHzp98UVpAiNK2p",
    "viewUrl": "https://drive.google.com/file/d/1WXjAKEJ2bZ4fRZsRQrHzp98UVpAiNK2p/view",
    "previewUrl": "https://drive.google.com/file/d/1WXjAKEJ2bZ4fRZsRQrHzp98UVpAiNK2p/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1WXjAKEJ2bZ4fRZsRQrHzp98UVpAiNK2p"
  },
  {
    "id": 14,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Físico",
    "name": "Memoria Geología",
    "type": "Documento",
    "format": "PDF",
    "study": "Geología",
    "driveId": "1L3SAX76II8RQ5LjwBMTkHjL4LLF-aMC5",
    "viewUrl": "https://drive.google.com/file/d/1L3SAX76II8RQ5LjwBMTkHjL4LLF-aMC5/view",
    "previewUrl": "https://drive.google.com/file/d/1L3SAX76II8RQ5LjwBMTkHjL4LLF-aMC5/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1L3SAX76II8RQ5LjwBMTkHjL4LLF-aMC5"
  },
  {
    "id": 15,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Físico",
    "name": "Memoria Geomorfología",
    "type": "Documento",
    "format": "PDF",
    "study": "Geomorfología",
    "driveId": "1xPHiYsOCAlTtO_Xe8TvayL_FcqDjh4jU",
    "viewUrl": "https://drive.google.com/file/d/1xPHiYsOCAlTtO_Xe8TvayL_FcqDjh4jU/view",
    "previewUrl": "https://drive.google.com/file/d/1xPHiYsOCAlTtO_Xe8TvayL_FcqDjh4jU/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1xPHiYsOCAlTtO_Xe8TvayL_FcqDjh4jU"
  },
  {
    "id": 16,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Físico",
    "name": "Memoria Fisiografía",
    "type": "Documento",
    "format": "PDF",
    "study": "Fisiografía",
    "driveId": "1Kw4QHV63uVDDvhOxwod-WMuU9v0BoTF9",
    "viewUrl": "https://drive.google.com/file/d/1Kw4QHV63uVDDvhOxwod-WMuU9v0BoTF9/view",
    "previewUrl": "https://drive.google.com/file/d/1Kw4QHV63uVDDvhOxwod-WMuU9v0BoTF9/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1Kw4QHV63uVDDvhOxwod-WMuU9v0BoTF9"
  },
  {
    "id": 17,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Físico",
    "name": "Memoria Suelos y CUM",
    "type": "Documento",
    "format": "PDF",
    "study": "Suelos y CUM",
    "driveId": "1igF8WHqWGW8phNCmfjPYJ1YgaSgFigKy",
    "viewUrl": "https://drive.google.com/file/d/1igF8WHqWGW8phNCmfjPYJ1YgaSgFigKy/view",
    "previewUrl": "https://drive.google.com/file/d/1igF8WHqWGW8phNCmfjPYJ1YgaSgFigKy/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1igF8WHqWGW8phNCmfjPYJ1YgaSgFigKy"
  },
  {
    "id": 18,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Biológico",
    "name": "Memoria Clima y Zonas de Vida",
    "type": "Documento",
    "format": "PDF",
    "study": "Clima y Zonas de Vida",
    "driveId": "1O7za6z1MO7vVyb_2kX44gI1LGqjDckqB",
    "viewUrl": "https://drive.google.com/file/d/1O7za6z1MO7vVyb_2kX44gI1LGqjDckqB/view",
    "previewUrl": "https://drive.google.com/file/d/1O7za6z1MO7vVyb_2kX44gI1LGqjDckqB/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1O7za6z1MO7vVyb_2kX44gI1LGqjDckqB"
  },
  {
    "id": 19,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Biológico",
    "name": "Memoria Fauna",
    "type": "Documento",
    "format": "PDF",
    "study": "Fauna",
    "driveId": "1ijlheCgaphGpYZjAcaCQFwXc9sXaIuiL",
    "viewUrl": "https://drive.google.com/file/d/1ijlheCgaphGpYZjAcaCQFwXc9sXaIuiL/view",
    "previewUrl": "https://drive.google.com/file/d/1ijlheCgaphGpYZjAcaCQFwXc9sXaIuiL/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1ijlheCgaphGpYZjAcaCQFwXc9sXaIuiL"
  },
  {
    "id": 20,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Biológico",
    "name": "Memoria Hidrobiológico",
    "type": "Documento",
    "format": "PDF",
    "study": "Hidrobiológico",
    "driveId": "1Irntb0W6XSaYCiHNpmQffylzUcT4irC4",
    "viewUrl": "https://drive.google.com/file/d/1Irntb0W6XSaYCiHNpmQffylzUcT4irC4/view",
    "previewUrl": "https://drive.google.com/file/d/1Irntb0W6XSaYCiHNpmQffylzUcT4irC4/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1Irntb0W6XSaYCiHNpmQffylzUcT4irC4"
  },
  {
    "id": 21,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Biológico",
    "name": "Memoria Forestal",
    "type": "Documento",
    "format": "PDF",
    "study": "Forestal",
    "driveId": "1c7bbVVkpUszYZOloDvhu4FCaaPTNKlY-",
    "viewUrl": "https://drive.google.com/file/d/1c7bbVVkpUszYZOloDvhu4FCaaPTNKlY-/view",
    "previewUrl": "https://drive.google.com/file/d/1c7bbVVkpUszYZOloDvhu4FCaaPTNKlY-/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1c7bbVVkpUszYZOloDvhu4FCaaPTNKlY-"
  },
  {
    "id": 22,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Sociocultural",
    "name": "Memoria Sociocultural",
    "type": "Documento",
    "format": "PDF",
    "study": "Sociocultural",
    "driveId": "1VCCEwXkH_OZBI6q3XcXESiF6No27ws4o",
    "viewUrl": "https://drive.google.com/file/d/1VCCEwXkH_OZBI6q3XcXESiF6No27ws4o/view",
    "previewUrl": "https://drive.google.com/file/d/1VCCEwXkH_OZBI6q3XcXESiF6No27ws4o/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1VCCEwXkH_OZBI6q3XcXESiF6No27ws4o"
  },
  {
    "id": 23,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Socioeconómico",
    "name": "Memoria Cobertura y Uso Actual del Territorio",
    "type": "Documento",
    "format": "PDF",
    "study": "Cobertura y Uso Actual del Territorio",
    "driveId": "1F0XJlWeYhi8VPpPEpDhJd1EtvrJVGcUr",
    "viewUrl": "https://drive.google.com/file/d/1F0XJlWeYhi8VPpPEpDhJd1EtvrJVGcUr/view",
    "previewUrl": "https://drive.google.com/file/d/1F0XJlWeYhi8VPpPEpDhJd1EtvrJVGcUr/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1F0XJlWeYhi8VPpPEpDhJd1EtvrJVGcUr"
  },
  {
    "id": 24,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Socioeconómico",
    "name": "Memoria Socioeconómico",
    "type": "Documento",
    "format": "PDF",
    "study": "Socioeconómico",
    "driveId": "1r7_LWknNkt8jBX9uVyakPTjDHz2TntLr",
    "viewUrl": "https://drive.google.com/file/d/1r7_LWknNkt8jBX9uVyakPTjDHz2TntLr/view",
    "previewUrl": "https://drive.google.com/file/d/1r7_LWknNkt8jBX9uVyakPTjDHz2TntLr/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1r7_LWknNkt8jBX9uVyakPTjDHz2TntLr"
  },
  {
    "id": 25,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Temáticos - Socioeconómico",
    "name": "Memoria Turismo",
    "type": "Documento",
    "format": "PDF",
    "study": "Turismo",
    "driveId": "1MR2R8rMhaMD083ocW_psqdy5_9JE4E4N",
    "viewUrl": "https://drive.google.com/file/d/1MR2R8rMhaMD083ocW_psqdy5_9JE4E4N/view",
    "previewUrl": "https://drive.google.com/file/d/1MR2R8rMhaMD083ocW_psqdy5_9JE4E4N/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1MR2R8rMhaMD083ocW_psqdy5_9JE4E4N"
  },
  {
    "id": 26,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Físico",
    "name": "Mapa CUM",
    "type": "Mapa",
    "format": "PDF",
    "study": "Suelos y CUM",
    "driveId": "1bJXpLfhkjd-paPAmkenOBIhaCU_K1m-6",
    "viewUrl": "https://drive.google.com/file/d/1bJXpLfhkjd-paPAmkenOBIhaCU_K1m-6/view",
    "previewUrl": "https://drive.google.com/file/d/1bJXpLfhkjd-paPAmkenOBIhaCU_K1m-6/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1bJXpLfhkjd-paPAmkenOBIhaCU_K1m-6"
  },
  {
    "id": 27,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Físico",
    "name": "Mapa Fisiografía",
    "type": "Mapa",
    "format": "PDF",
    "study": "Fisiografía",
    "driveId": "1J3ycBFA0dNdG8GLRBOCiFPd3wTE-Q6jq",
    "viewUrl": "https://drive.google.com/file/d/1J3ycBFA0dNdG8GLRBOCiFPd3wTE-Q6jq/view",
    "previewUrl": "https://drive.google.com/file/d/1J3ycBFA0dNdG8GLRBOCiFPd3wTE-Q6jq/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1J3ycBFA0dNdG8GLRBOCiFPd3wTE-Q6jq"
  },
  {
    "id": 28,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Físico",
    "name": "Mapa Geología",
    "type": "Mapa",
    "format": "PDF",
    "study": "Geología",
    "driveId": "1PDSRCdTpvHGiSStt11QyS8Xu7WbjxmTK",
    "viewUrl": "https://drive.google.com/file/d/1PDSRCdTpvHGiSStt11QyS8Xu7WbjxmTK/view",
    "previewUrl": "https://drive.google.com/file/d/1PDSRCdTpvHGiSStt11QyS8Xu7WbjxmTK/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1PDSRCdTpvHGiSStt11QyS8Xu7WbjxmTK"
  },
  {
    "id": 29,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Físico",
    "name": "Mapa Geomorfología",
    "type": "Mapa",
    "format": "PDF",
    "study": "Geomorfología",
    "driveId": "1uBZelN1z1m5FCMi7l_qxive88YjcR9ib",
    "viewUrl": "https://drive.google.com/file/d/1uBZelN1z1m5FCMi7l_qxive88YjcR9ib/view",
    "previewUrl": "https://drive.google.com/file/d/1uBZelN1z1m5FCMi7l_qxive88YjcR9ib/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1uBZelN1z1m5FCMi7l_qxive88YjcR9ib"
  },
  {
    "id": 30,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Físico",
    "name": "Mapa Suelos",
    "type": "Mapa",
    "format": "PDF",
    "study": "Suelos y CUM",
    "driveId": "1FW_Zu36QcoOLokCVDF1wfMHbvMCJmxu9",
    "viewUrl": "https://drive.google.com/file/d/1FW_Zu36QcoOLokCVDF1wfMHbvMCJmxu9/view",
    "previewUrl": "https://drive.google.com/file/d/1FW_Zu36QcoOLokCVDF1wfMHbvMCJmxu9/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1FW_Zu36QcoOLokCVDF1wfMHbvMCJmxu9"
  },
  {
    "id": 31,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Biológico",
    "name": "Mapa Zonas de Vida",
    "type": "Mapa",
    "format": "JPG",
    "study": "Clima y Zonas de Vida",
    "driveId": "1bmH0Kg8zVdroeKqflmXymTnOWAOa2NeN",
    "viewUrl": "https://drive.google.com/file/d/1bmH0Kg8zVdroeKqflmXymTnOWAOa2NeN/view",
    "previewUrl": "https://drive.google.com/file/d/1bmH0Kg8zVdroeKqflmXymTnOWAOa2NeN/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1bmH0Kg8zVdroeKqflmXymTnOWAOa2NeN"
  },
  {
    "id": 32,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Biológico",
    "name": "Mapa Hidrobiológico",
    "type": "Mapa",
    "format": "JPG",
    "study": "Hidrobiológico",
    "driveId": "1idScQupu8F7U9VP6vqSMuJAnoh-XaOSJ",
    "viewUrl": "https://drive.google.com/file/d/1idScQupu8F7U9VP6vqSMuJAnoh-XaOSJ/view",
    "previewUrl": "https://drive.google.com/file/d/1idScQupu8F7U9VP6vqSMuJAnoh-XaOSJ/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1idScQupu8F7U9VP6vqSMuJAnoh-XaOSJ"
  },
  {
    "id": 33,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Biológico",
    "name": "Mapa Forestal",
    "type": "Mapa",
    "format": "JPG",
    "study": "Forestal",
    "driveId": "1unACkcLegdjpBvtm9JHG5u0xgER0B4pk",
    "viewUrl": "https://drive.google.com/file/d/1unACkcLegdjpBvtm9JHG5u0xgER0B4pk/view",
    "previewUrl": "https://drive.google.com/file/d/1unACkcLegdjpBvtm9JHG5u0xgER0B4pk/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1unACkcLegdjpBvtm9JHG5u0xgER0B4pk"
  },
  {
    "id": 34,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Biológico",
    "name": "Mapa Fauna",
    "type": "Mapa",
    "format": "JPG",
    "study": "Fauna",
    "driveId": "1eX4gg21dZAOdxwerTUy6oulseHjiJxSW",
    "viewUrl": "https://drive.google.com/file/d/1eX4gg21dZAOdxwerTUy6oulseHjiJxSW/view",
    "previewUrl": "https://drive.google.com/file/d/1eX4gg21dZAOdxwerTUy6oulseHjiJxSW/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1eX4gg21dZAOdxwerTUy6oulseHjiJxSW"
  },
  {
    "id": 35,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Sociocultural",
    "name": "Mapa Potencial Sociocultural",
    "type": "Mapa",
    "format": "JPG",
    "study": "Sociocultural",
    "driveId": "1JnLO4lhH7esMAOIxeYZ_Sn-ozye6GiRb",
    "viewUrl": "https://drive.google.com/file/d/1JnLO4lhH7esMAOIxeYZ_Sn-ozye6GiRb/view",
    "previewUrl": "https://drive.google.com/file/d/1JnLO4lhH7esMAOIxeYZ_Sn-ozye6GiRb/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1JnLO4lhH7esMAOIxeYZ_Sn-ozye6GiRb"
  },
  {
    "id": 36,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Socioeconómico",
    "name": "Mapa Cobertura y Uso Actual",
    "type": "Mapa",
    "format": "JPG",
    "study": "Cobertura y Uso Actual del Territorio",
    "driveId": "199gO002XT_1SL_6XDvAfqxmrf-00vaad",
    "viewUrl": "https://drive.google.com/file/d/199gO002XT_1SL_6XDvAfqxmrf-00vaad/view",
    "previewUrl": "https://drive.google.com/file/d/199gO002XT_1SL_6XDvAfqxmrf-00vaad/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=199gO002XT_1SL_6XDvAfqxmrf-00vaad"
  },
  {
    "id": 37,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Socioeconómico",
    "name": "Mapa Potencial Turístico",
    "type": "Mapa",
    "format": "JPG",
    "study": "Turismo",
    "driveId": "1JMcvH5N-9s4TCx6os8zDcs50piWKdpig",
    "viewUrl": "https://drive.google.com/file/d/1JMcvH5N-9s4TCx6os8zDcs50piWKdpig/view",
    "previewUrl": "https://drive.google.com/file/d/1JMcvH5N-9s4TCx6os8zDcs50piWKdpig/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1JMcvH5N-9s4TCx6os8zDcs50piWKdpig"
  },
  {
    "id": 38,
    "category": "Ordenamiento Territorial",
    "section": "Memorias de estudios temáticos y ZEE",
    "group": "Mapas - Socioeconómico",
    "name": "Mapa Socioeconómico",
    "type": "Mapa",
    "format": "JPG",
    "study": "Socioeconómico",
    "driveId": "1AAjWQwiEVv_SVfYrhdrSZitAIl1vRklq",
    "viewUrl": "https://drive.google.com/file/d/1AAjWQwiEVv_SVfYrhdrSZitAIl1vRklq/view",
    "previewUrl": "https://drive.google.com/file/d/1AAjWQwiEVv_SVfYrhdrSZitAIl1vRklq/preview",
    "downloadUrl": "https://drive.google.com/uc?export=download&id=1AAjWQwiEVv_SVfYrhdrSZitAIl1vRklq"
  }
];
